### ISSUE TITLE
RFC: Add metadata specification management

### ISSUE THREAD

**Issue by marrws** [nullplatform/terraform-provider-nullplatform#39]
At the time your API allows for a complete CRUD[^1][^2][^3][^4][^5] of metadata specification. Is this feature in the roadmap of this provider?

[^1]: https://docs.nullplatform.com/api/list-metadata-specifications
[^2]: https://docs.nullplatform.com/api/create-a-entity-metadata-specification
[^3]: https://docs.nullplatform.com/api/read-a-entity-metadata-specification
[^4]: https://docs.nullplatform.com/api/update-a-entity-metadata-specification
[^5]: https://docs.nullplatform.com/api/delete-a-entity-metadata-specification

**Comment by sebasnallar** [comment]
@marrws listing through specifications won't be necessary for the needs of the provider itself, so i guess that one is out of the scope
